# Generated by Django 5.2.15 on 2026-07-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('source', models.CharField(choices=[('strava', 'Strava'), ('zepp', 'Zepp'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('activity_type', models.CharField(blank=True, max_length=64)),
                ('start_date', models.DateTimeField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('moving_time_min', models.FloatField(blank=True, null=True)),
                ('avg_hr', models.FloatField(blank=True, null=True)),
                ('max_hr', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'You'), ('assistant', 'Coach')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('hrv', models.FloatField(blank=True, help_text='ms', null=True)),
                ('rhr', models.PositiveIntegerField(blank=True, help_text='resting heart rate, bpm', null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('sleep_score', models.PositiveIntegerField(blank=True, help_text='0-100 if your device provides one', null=True)),
                ('body_battery', models.PositiveIntegerField(blank=True, help_text='0-100 readiness/energy score, if available', null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='How you feel, soreness, stress, life stuff, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StravaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.BigIntegerField()),
                ('athlete_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('workout_type', models.CharField(blank=True, help_text='e.g. easy run, intervals, strength, rest', max_length=64)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=10)),
                ('source', models.CharField(choices=[('llm', 'AI Coach'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
