# Generated by Django 5.2.15 on 2026-07-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='elevation_gain_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.CharField(choices=[('strava', 'Strava'), ('zepp', 'Zepp'), ('gpx', 'GPX upload'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
    ]
