# Generated by Django 5.2.15 on 2026-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Shin splints (left leg)'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Details, cause, what to avoid, etc.')),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, help_text='Leave blank if unknown', null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='StravaToken',
        ),
        migrations.AddField(
            model_name='workout',
            name='avg_hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='elevation_gain_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Dedup key for imports, e.g. gpx filename+timestamp', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='max_hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='moving_time_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='source',
            field=models.CharField(choices=[('llm', 'AI Coach'), ('manual', 'Manual'), ('gpx', 'GPX upload')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(blank=True, help_text='e.g. easy run, intervals, cycling, strength, rest', max_length=64),
        ),
    ]
