# Generated by Django 5.2.15 on 2026-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_activecondition_delete_activity_delete_stravatoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrv_baseline', models.FloatField(blank=True, help_text='ms - leave blank to auto-compute from your last 30 days', null=True)),
                ('rhr_baseline', models.PositiveIntegerField(blank=True, help_text='bpm - leave blank to auto-compute from your last 30 days', null=True)),
                ('max_hr', models.PositiveIntegerField(blank=True, help_text='Known max heart rate, if you have it', null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text="Used to estimate max HR (220-age) if max HR isn't set", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'City Marathon'", max_length=255)),
                ('event_date', models.DateField()),
                ('target_distance_km', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
